Repository eProsima/Fast-DDS-docs, pull requests merged in 2023-02, with the labels that each got.

#458 [17046] Add angle brackets to missing elements in locators XML profile
  docs/fastdds/xml_configuration/common.rst
  docs/fastdds/xml_configuration/domainparticipant.rst
  docs/fastdds/xml_configuration/dynamic_types.rst
Labels: ready, skip-ci, no-test

#460 Remove 2.9.x from mirror
  .github/workflows/mirror.yml
Labels: skip-ci

#461 [17153] Set TLS verify paths as list of strings (transport descriptors)
  docs/fastdds/xml_configuration/transports.rst
Labels: enhancement, skip-ci, no-test

#462 [17031] Common & DomainParticipant xml profiles typos
  docs/fastdds/xml_configuration/common.rst
  docs/fastdds/xml_configuration/domainparticipant.rst
Labels: enhancement
