Repository eProsima/Fast-DDS-docs, pull requests merged in 2024-07, with the labels that each got.

#831 [21256] Migrate Fast DDS Docs CI to Github
  .github/workflows/config/build.meta
  .github/workflows/config/test.meta
  .github/workflows/config/test.repos
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/ubuntu-ci.yml
  RELEASE_SUPPORT.md
  docs/notes/versions.rst
Labels: ready-to-merge

#838 [21256] Fix issue with Fast DDS and Fast DDS python deduced branches
  .github/workflows/reusable-ubuntu-ci.yml
Labels: ready-to-merge

#751 [20629] GUIDLess Discovery Server
  code/DDSCodeTester.cpp
  code/XMLTester.xml
  code/XMLTesterExample.xml
  docs/03-exports/aliases-api.include
  docs/fastdds/api_reference/rtps/attributes/RemoteServerAttributes.rst
  docs/fastdds/api_reference/rtps/attributes/RemoteServerList_t.rst
  docs/fastdds/api_reference/rtps/attributes/attributes.rst
  docs/fastdds/discovery/discovery_server.rst
  docs/fastdds/env_vars/env_vars.rst
  docs/fastdds/ros2/discovery_server/ros2_discovery_server.rst
  docs/fastdds/ros2/discovery_server/super_client_configuration_file.xml
  docs/fastdds/transport/transport_api.rst
  docs/fastdds/use_cases/tcp/tcp_with_discovery_server.rst
  docs/fastdds/use_cases/wifi/discovery_server_use_case.rst
  docs/fastdds/xml_configuration/domainparticipant.rst
  docs/fastddscli/cli/cli.rst
Labels: ci-pending

#818 [21184] Adjust type in get_dynamic_type_builder_from_xml_by_name to return DynamicTypeBuilder
  code/DDSCodeTester.cpp
Labels: ci-pending

#843 [21244] Bump version to v2.6.9
  docs/conf.py
  docs/notes/notes.rst
  docs/notes/previous_versions/v2.6.8.rst
  docs/spelling_wordlist.txt
Labels: ci-pending

#811 [21155] Improve build steps in the installation from sources sections
  docs/installation/sources/sources_linux.rst
  docs/installation/sources/sources_mac.rst
  docs/installation/sources/sources_qnx.rst
  docs/installation/sources/sources_windows.rst
Labels: ready-to-merge

#807 [21100] Include v2.13.5 release notes in master
  docs/notes/previous_versions/supported_versions.rst
  docs/notes/previous_versions/v2.13.5.rst
  docs/notes/versions.rst
  docs/spelling_wordlist.txt
Labels: ready-to-merge, ci-pending

#845 [21256] Fix nightly job and move 2.6.x to weekly CI
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/weekly-ubuntu-ci.yml
Labels: skip-ci

#837 [21290] Update to doxygen 1.9.8 used in Ubuntu 24.04
  .github/workflows/reusable-ubuntu-ci.yml
  code/doxygen-config.in
  docs/conf.py
  docs/fastdds/api_reference/rtps/common/CacheChange/ChangeKind_t.rst
  readthedocs.yaml
Labels: ready-to-merge, skip-ci

#848 [21244] Include v2.6.9 release notes and `2.6.x` maintenance flag
  docs/notes/previous_versions/supported_versions.rst
  docs/notes/previous_versions/v2.6.9.rst
  docs/notes/versions.rst
  docs/spelling_wordlist.txt
Labels: ready-to-merge

#852 [21267] Fix weekly CI cron expression
  .github/workflows/weekly-ubuntu-ci.yml
Labels: skip-ci

#855 [21320] Fix master references in stable version
  README.md
  docs/fastdds/discovery/discovery_server.rst
  docs/fastdds/discovery/static.rst
  docs/fastdds/dynamic_types/examples.rst
  docs/fastdds/getting_started/simple_app/includes/publisher.rst
  docs/fastdds/getting_started/simple_app/includes/subscriber.rst
  docs/fastdds/getting_started/simple_app/includes/sum_and_next_steps.rst
  docs/fastdds/getting_started/simple_python_app/includes/publisher.rst
  docs/fastdds/getting_started/simple_python_app/includes/subscriber.rst
  docs/fastdds/getting_started/simple_python_app/includes/sum_and_next_steps.rst
  docs/fastdds/rtps_layer/rtps_layer.rst
  docs/fastdds/security/access_control_plugin/access_control_plugin.rst
  docs/fastdds/transport/shared_memory/shared_memory.rst
  docs/fastdds/transport/tcp/tcp.rst
  docs/fastdds/use_cases/request_reply/request_reply.rst
  docs/fastdds/use_cases/statistics_module/statistics_module.rst
  docs/fastdds/use_cases/well_known_deployments/well_known_deployments.rst
  docs/fastdds/use_cases/zero_copy/zero_copy.rst
  docs/fastdds/xml_configuration/making_xml_profiles.rst
  docs/fastddsgen/pubsub_app/includes/sum_and_next_steps.rst
  docs/fastddsgen/usage/usage.rst
  docs/installation/configuration/cmake_options.rst
  docs/installation/sources/sources_linux.rst
  docs/installation/sources/sources_mac.rst
  docs/installation/sources/sources_windows.rst
Labels: ready-to-merge

#857 [21309] Change back Ubuntu versions for CI and RTD
  .github/workflows/reusable-ubuntu-ci.yml
  docs/conf.py
  readthedocs.yaml
Labels: ready-to-merge

#846 [21299] Fix code block not been colored after sphinx upgrade
  docs/conf.py
Labels: ci-pending

#847 [21137] Account for changes on RTPS writer refactor
  code/DDSCodeTester.cpp
  code/XMLTester.xml
  code/XMLTesterExample.xml
  docs/03-exports/aliases-api.include
  docs/fastdds/api_reference/spelling_wordlist.txt
  docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
  docs/fastdds/property_policies/non_consolidated_qos.rst
  docs/fastdds/xml_configuration/datawriter.rst
Labels: ci-pending

#853 [21319] Add python optional step in binary installation sections
  docs/installation/binaries/binaries_linux.rst
  docs/installation/binaries/binaries_windows.rst
Labels: ready-to-merge

#844 [20903] Documentation to serialize DynamicData to JSON
  code/DDSCodeTester.cpp
  code/DynamicTypesIDLExamples.idl
  code/json/Arrays.json
  code/json/Bitmask_EPROSIMA.json
  code/json/Bitmask_OMG.json
  code/json/Bitsets.json
  code/json/Enum_EPROSIMA.json
  code/json/Enum_OMG.json
  code/json/Maps.json
  code/json/Primitives.json
  code/json/Sequences.json
  code/json/Strings.json
  code/json/Structs.json
  code/json/Unions.json
  docs/03-exports/aliases-api.include
  docs/fastdds/api_reference/dds_pim/xtypes/utils.rst
  docs/fastdds/api_reference/dds_pim/xtypes/xtypes.rst
  docs/fastdds/api_reference/spelling_wordlist.txt
  docs/fastdds/xtypes/type_serializing.rst
  docs/fastdds/xtypes/xtypes.rst
Labels: ci-pending

#867 [21311] Bump version to 2.14.3
  docs/conf.py
  docs/notes/notes.rst
  docs/notes/previous_versions/supported_versions.rst
  docs/notes/previous_versions/v2.14.2.rst
  docs/notes/previous_versions/v2.14.3.rst
  docs/notes/versions.rst
Labels: ci-pending

#865 [21051] Documentation to serialize DynamicTypes to IDL
  code/DDSCodeTester.cpp
  docs/03-exports/aliases-api.include
  docs/fastdds/api_reference/dds_pim/xtypes/utils.rst
  docs/fastdds/xtypes/language_binding.rst
  docs/fastdds/xtypes/type_serializing.rst
Labels: ci-pending

#869 [21311] Add Fast DDS v2.14.3 release notes (#867)
  docs/notes/notes.rst
  docs/notes/previous_versions/supported_versions.rst
  docs/notes/previous_versions/v2.14.2.rst
  docs/notes/previous_versions/v2.14.3.rst
  docs/notes/versions.rst
Labels: ci-pending

#868 [21310] Bump version to v2.13.6
  docs/conf.py
  docs/notes/notes.rst
  docs/notes/previous_versions/v2.13.0.rst
  docs/notes/previous_versions/v2.13.1.rst
  docs/notes/previous_versions/v2.13.2.rst
  docs/notes/previous_versions/v2.13.3.rst
  docs/notes/previous_versions/v2.13.4.rst
  docs/notes/previous_versions/v2.13.5.rst
Labels: ready-to-merge

#871 [21310] Set 2.13.x as EOL
  .github/pull_request_template.md
  .github/workflows/nightly-ubuntu-ci.yml
  docs/notes/previous_versions/previous_versions.rst
  docs/notes/previous_versions/supported_versions.rst
  docs/notes/previous_versions/v2.13.0.rst
  docs/notes/previous_versions/v2.13.1.rst
  docs/notes/previous_versions/v2.13.2.rst
  docs/notes/previous_versions/v2.13.3.rst
  docs/notes/previous_versions/v2.13.4.rst
  docs/notes/previous_versions/v2.13.5.rst
  docs/notes/previous_versions/v2.13.6.rst
  docs/notes/versions.rst
Labels: ci-pending

#866 [21301] Remove `WriterProxyData` from public APIs
  code/CMakeLists.txt
  code/DDSCodeTester.cpp
  docs/fastdds/api_reference/rtps/builtin/data/PublicationBuiltinTopicData.rst
  docs/fastdds/api_reference/rtps/builtin/data/data.rst
  docs/fastdds/api_reference/rtps/participant/participantdiscoveryinfo/WriterDiscoveryInfo.rst
  docs/fastdds/api_reference/rtps/participant/participantdiscoveryinfo/WriterDiscoveryStatus.rst
  docs/fastdds/api_reference/rtps/participant/participantdiscoveryinfo/WriterProxyData.rst
  docs/fastdds/api_reference/rtps/participant/participantdiscoveryinfo/participantdiscoveryinfo.rst
Labels: ready-to-merge

#876 [21309] CI: `paths-ignore` only ignores modification in markdown files
  .github/workflows/ubuntu-ci.yml
Labels: ready-to-merge

#875 [21378] Refactor `TopicDataType`
  code/CodeTester.cpp
  code/DDSCodeTester.cpp
  code/Examples/C++/DDSHelloWorld/src/HelloWorldPubSubTypes.cxx
  code/Examples/C++/DDSHelloWorld/src/HelloWorldPubSubTypes.hpp
Labels: ready-to-merge

#870 [21321] Move `Time_t` to `dds` namespace and some *Attributes to `xmlparser` docs
  code/DDSCodeTester.cpp
  docs/03-exports/aliases-api.include
  docs/fastdds/api_reference/dds_pim/core/Time_t/Duration_t.rst
  docs/fastdds/api_reference/dds_pim/core/Time_t/Time_t.rst
  docs/fastdds/api_reference/dds_pim/core/Time_t/const_values.rst
  docs/fastdds/api_reference/dds_pim/core/Time_t/operators.rst
  docs/fastdds/api_reference/dds_pim/core/Time_t/time_toc.rst
  docs/fastdds/api_reference/dds_pim/core/core.rst
  docs/fastdds/api_reference/rtps/common/Time_t/Duration_t.rst
  docs/fastdds/api_reference/rtps/common/Time_t/Time_t.rst
  docs/fastdds/api_reference/rtps/common/Time_t/const_values.rst
  docs/fastdds/api_reference/rtps/common/Time_t/fastrtps_Time_t.rst
  docs/fastdds/api_reference/rtps/common/Time_t/operators.rst
  docs/fastdds/api_reference/rtps/common/Time_t/time_toc.rst
Labels: ci-pending

#874 [21295] Participant discovery data refactor
  code/DDSCodeTester.cpp
  docs/fastdds/api_reference/rtps/builtin/data/ParticipantBuiltinTopicData.rst
  docs/fastdds/api_reference/rtps/builtin/data/data.rst
  docs/fastdds/api_reference/rtps/participant/participantdiscoveryinfo/ParticipantDiscoveryInfo_class.rst
  docs/fastdds/api_reference/rtps/participant/participantdiscoveryinfo/ParticipantDiscoveryStatus.rst
  docs/fastdds/api_reference/rtps/participant/participantdiscoveryinfo/ParticipantProxyData.rst
  docs/fastdds/api_reference/rtps/participant/participantdiscoveryinfo/participantdiscoveryinfo.rst
Labels: ci-pending

#794 [21136] Fix Large data usecase flowcontrollers XML snippet
  docs/fastdds/use_cases/large_data/large_data.rst
Labels: ci-pending, needs-review

#880 [21313] Type propagation policy
  code/DDSCodeTester.cpp
  code/XMLTester.xml
  docs/fastdds/api_reference/spelling_wordlist.txt
  docs/fastdds/property_policies/non_consolidated_qos.rst
  docs/fastdds/xtypes/discovery_matching.rst
Labels: ci-pending

#881 Fix README and standardQosPolicies
  README.md
  docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
Labels: ci-pending
