Repository eProsima/Fast-DDS-docs, pull requests merged in 2024-02, with the labels that each got.

#650 Expose PayloadPool in DDSDataWriter and DDSDataReader (backport #514)
  code/DDSCodeTester.cpp
  docs/fastdds/dds_layer/publisher/dataWriter/createDataWriter.rst
  docs/fastdds/dds_layer/subscriber/dataReader/createDataReader.rst
  docs/fastdds/rtps_layer/rtps_layer.rst
Labels: ci-pending

#621 Bump version to 2.11.3
  docs/conf.py
  docs/notes/notes.rst
  docs/notes/previous_versions/v2.11.0.rst
  docs/notes/previous_versions/v2.11.1.rst
  docs/notes/previous_versions/v2.11.2.rst
  docs/spelling_wordlist.txt
Labels: ready-to-merge

#671 [20501] Improve LARGE_DATA documentation
  code/XMLTester.xml
  docs/fastdds/rtps_layer/rtps_layer.rst
  docs/fastdds/transport/tcp/tcp.rst
  docs/fastdds/troubleshooting/troubleshooting.rst
  docs/fastdds/use_cases/large_data/large_data.rst
  docs/fastdds/use_cases/tcp/tcp_with_multicast_discovery.rst
Labels: to-do

#664 [20401] Improve History QoS documentation and compatibility rules
  docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
Labels: ready-to-merge

#673 Include Fast DDS v2.11.3 release notes
  docs/notes/notes.rst
  docs/notes/previous_versions/v2.11.3.rst
Labels: ci-pending

#679 [20503] Clarify history depth vs max_samples_per_instance inconsistency
  docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
Labels: ci-pending

#682 [20505] Bump version to v2.13.3
  docs/conf.py
  docs/notes/notes.rst
  docs/notes/previous_versions/v2.13.2.rst
Labels: skip-ci

#683 [20414] Bump version to 2.14.0
  .github/pull_request_template.md
  .github/workflows/mirror.yml
  colcon.meta
  docs/conf.py
Labels: ready-to-merge

#684 [20486] Fix release notes title
  docs/notes/previous_versions/v2.11.3.rst
Labels: ci-pending

#685 [20486] Fix typo in v2.13.3 release notes
  docs/notes/notes.rst
Labels: ci-pending

#690 [20527] Ignore FASTDDS_TODO_BEFORE macro on doxygen generation
  code/doxygen-config.in
Labels: ready-to-merge

#678 [20502] TCP non_blocking_send moved to TCPTransportDescriptor
  code/DDSCodeTester.cpp
  code/XMLTester.xml
  docs/03-exports/aliases-api.include
  docs/fastdds/property_policies/non_consolidated_qos.rst
  docs/fastdds/transport/tcp/tcp.rst
  docs/fastdds/xml_configuration/transports.rst
Labels: ready-to-merge

#697 [19175] Documentation of FASTDDS_EXAMPLE_TESTS CMake option
  docs/installation/configuration/cmake_options.rst
Labels: ready-to-merge
