Repository eProsima/Fast-DDS-docs, pull requests merged in 2024-03, with the labels that each got.

#700 [20501] Rearrange use cases list
  docs/fastdds/use_cases/tcp/tcp_use_case.rst
  docs/fastdds/use_cases/tcp/tcp_with_multicast_discovery.rst
  docs/fastdds/use_cases/use_cases.rst
Labels: ready-to-merge

#717 [20313] Allow single listening port on TCP
  docs/fastdds/transport/tcp/tcp.rst
Labels: ready-to-merge

#699 [20508] TCP first message loss
  docs/03-exports/aliases-api.include
  docs/fastdds/transport/tcp/tcp.rst
  docs/fastdds/xml_configuration/transports.rst
Labels: ci-pending

#696 [20493] Extend LARGE_DATA configuration options
  code/DDSCodeTester.cpp
  code/XMLTester.xml
  code/XMLTesterExample.xml
  docs/fastdds/env_vars/env_vars.rst
  docs/fastdds/rtps_layer/rtps_layer.rst
  docs/fastdds/troubleshooting/troubleshooting.rst
  docs/fastdds/use_cases/tcp/tcp_large_data_with_options.rst
  docs/fastdds/use_cases/tcp/tcp_use_case.rst
  docs/fastdds/xml_configuration/common.rst
  docs/fastdds/xml_configuration/domainparticipant.rst
  docs/spelling_wordlist.txt
Labels: ready-to-merge

#720 [20551] Modify statistic data writer profile name in the xml file
  code/XMLTester.xml
Labels: ready-to-merge

#727 Downgrade cmake version to 3.20
  CMakeLists.txt
  code/Examples/C++/DDSHelloWorld/CMakeLists.txt
Labels: ci-pending

#659 [19778][20296] Add netmask filter transport configuration + interface allowlist and blocklist
  code/DDSCodeTester.cpp
  code/XMLTester.xml
  code/XMLTesterExample.xml
  docs/03-exports/aliases-api.include
  docs/fastdds/api_reference/spelling_wordlist.txt
  docs/fastdds/transport/interfaces.rst
  docs/fastdds/transport/tcp/tcp.rst
  docs/fastdds/transport/transport.rst
  docs/fastdds/transport/transport_api.rst
  docs/fastdds/transport/udp/udp.rst
  docs/fastdds/transport/whitelist.rst
  docs/fastdds/xml_configuration/domainparticipant.rst
  docs/fastdds/xml_configuration/transports.rst
Labels: ready-to-merge

#729 [20501] Clarify how sockets_size affects SHM segment size
  docs/fastdds/use_cases/tcp/tcp_large_data_with_options.rst
Labels: needs-review

#734 [20644] Remove latest mark from 2.13.3
  docs/notes/previous_versions/v2.13.3.rst
Labels: ci-pending

#733 [20553] Set 2.12.x as EOL
  .github/pull_request_template.md
  docs/notes/previous_versions/previous_versions.rst
  docs/notes/previous_versions/supported_versions.rst
  docs/notes/previous_versions/v2.12.0.rst
  docs/notes/previous_versions/v2.12.1.rst
  docs/notes/versions.rst
Labels: ci-pending
