Repository eProsima/Fast-DDS-docs, pull requests merged in 2024-10, with the labels that each got.

#921 [21557] Add notes from v2.10.5
  docs/notes/previous_versions/supported_versions.rst
  docs/notes/previous_versions/v2.10.5.rst
  docs/notes/versions.rst
Labels: ready-to-merge, ci-pending

#923 [21784] Bump version to v3.1.0
  .github/pull_request_template.md
  .github/workflows/mirror.yml
  .github/workflows/nightly-ubuntu-ci.yml
  docs/conf.py
Labels: ci-pending

#924 [21784] Branch out 3.0.x
  .github/workflows/mirror.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/ubuntu-ci.yml
  .github/workflows/weekly-ubuntu-ci.yml
Labels: ci-pending

#907 [21538] Allow all `durability` configurations
  docs/fastdds/dds_layer/core/policy/standardQosPolicies.rst
  docs/fastdds/persistence/persistence.rst
Labels: ready-to-merge

#925 [21564] Update `fastdds_profiles.xsd` file location
  code/CMakeLists.txt
Labels: ready-to-merge

#927 [21821] Update Use Case: How to use eProsima DDS Record and Replay
  docs/01-figures/fast_dds/recorder_shapesdemo_exec.png
  docs/01-figures/fast_dds/recorder_shapesdemo_publisher.png
  docs/04-common/python_requirements.rst
  docs/fastdds/use_cases/dds_record_and_replay/dds_record_and_replay.rst
  docs/fastdds/use_cases/rosbag_capture/rosbag_capture.rst
  docs/fastdds/use_cases/use_cases.rst
Labels: ci-pending

#928 [21745] Add QoS getters from raw XML
  code/DDSCodeTester.cpp
  docs/03-exports/aliases-api.include
  docs/fastdds/dds_layer/domain/domainParticipant/domainParticipant.rst
  docs/fastdds/use_cases/dds_record_and_replay/dds_record_and_replay.rst
  docs/fastdds/use_cases/use_cases.rst
  docs/fastdds/xml_configuration/making_xml_profiles.rst
Labels: ci-pending

#929 [21797] Add Fast DDS v3 Migration Guide
  docs/index.rst
  docs/installation/configuration/cmake_options.rst
  docs/notes/migration_guide.rst
  docs/spelling_wordlist.txt
Labels: ready-to-merge

#930 [21783] Add notes for Fast DDS `v3.1.0`
  docs/notes/migration_guide.rst
  docs/notes/notes.rst
  docs/notes/previous_versions/supported_versions.rst
  docs/notes/previous_versions/v3.0.1.rst
  docs/notes/previous_versions/v3.1.0.rst
  docs/notes/versions.rst
Labels: ci-pending

#931 [21873] Update commercial support section
  docs/02-formalia/titlepage.rst
Labels: ci-pending

#932 [21890] Update commercial support section in project README
  README.md
  docs/02-formalia/titlepage.rst
Labels: skip-ci

#933 [21907] Include link to Python installation Getting started
  docs/fastdds/getting_started/simple_python_app/includes/prerequisites.rst
  docs/fastdds/getting_started/simple_python_app/simple_python_app.rst
Labels: ready-to-merge

#934 [21908] Adjust XML snippets to meet QoS constraints
  code/DDSCodeTester.cpp
  code/XMLTester.xml
Labels: ready-to-merge

#939 [21882] Branch out 3.2.x
  .github/pull_request_template.md
  .github/workflows/mirror.yml
  .github/workflows/nightly-ubuntu-ci.yml
  docs/conf.py
Labels: ci-pending

#940 [21882] Branch out 3.1.x
  .github/workflows/mirror.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/ubuntu-ci.yml
  .github/workflows/weekly-ubuntu-ci.yml
Labels: skip-ci
