Repository eProsima/Fast-DDS-docs, pull requests merged in 2024-09, with the labels that each got.

#896 [21443] Fix bug in initial peers documentation
  docs/fastdds/discovery/simple.rst
Labels: ready-to-merge

#894 fix(fastdds):fix fastdds discovery docs error
  docs/fastdds/discovery/includes/disc_phases.rst
Labels: needs-review

#768 [21580] Improve `mutation_tries` documentation
  code/DDSCodeTester.cpp
  code/XMLTester.xml
  docs/fastdds/dds_layer/core/policy/eprosimaExtensions.rst
  docs/fastdds/transport/listening_locators.rst
Labels: ci-pending

#906 [21590] Add warning about idls extensibility for Vulcanexus jazzy
  docs/fastdds/use_cases/rosbag_capture/rosbag_capture.rst
Labels: ci-pending

#908 [21561] Bump version to 3.0.1
  docs/conf.py
  docs/notes/notes.rst
  docs/notes/previous_versions/v3.0.0.rst
  docs/notes/previous_versions/v3.0.1.rst
  docs/notes/versions.rst
Labels: ready-to-merge

#909 [21663] Update release notes with latest PR merged
  docs/notes/previous_versions/v3.0.1.rst
Labels: ci-pending

#911 [21646] Fix typo in statistics troubleshooting XML snippet
  code/XMLTester.xml
  docs/fastdds/statistics/dds_layer/troubleshooting.rst
Labels: ci-pending

#912 [21655] Mirror `2.6.9` with `2.6.x` ci job
  .github/workflows/mirror.yml
Labels: skip-ci

#856 [21578] Fix master build to run on Ubuntu 24.04
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/ubuntu-ci.yml
Labels: ready-to-merge

#910 [21655] Add default subscriber profile in ROS 2 XML configuration
  code/XMLTester.xml
Labels: ci-pending

#902 [21416] Enhance Fast DDS docs with a FAQs section covering every subsection
  docs/02-formalia/titlepage.rst
  docs/03-exports/aliases-api.include
  docs/conf.py
  docs/fastdds/api_reference/rtps/participant/participantdiscoveryinfo/ParticipantDiscoveryStatus.rst
  docs/fastdds/faq/dds_layer/dds_layer.rst
  docs/fastdds/faq/discovery/discovery.rst
  docs/fastdds/faq/environment_variables/environment_variables.rst
  docs/fastdds/faq/faq.rst
  docs/fastdds/faq/getting_started/getting_started.rst
  docs/fastdds/faq/logging/logging.rst
  docs/fastdds/faq/persistence_service/persistence_service.rst
  docs/fastdds/faq/rtps_layer/rtps_layer.rst
  docs/fastdds/faq/security/security.rst
  docs/fastdds/faq/statistics_module/statistics_module.rst
  docs/fastdds/faq/transport_layer/transport_layer.rst
  docs/fastdds/faq/xml_profiles/xml_profiles.rst
  docs/fastdds/faq/xtypes/xtypes.rst
  docs/fastdds/statistics/monitor_service/intro.rst
  docs/index.rst
  docs/requirements.txt
  docs/spelling_wordlist.txt
Labels: ready-to-merge

#917 [21750] Add support @value annotation on fastddsgen
  code/FastDDSGenCodeTester.cpp
  docs/fastdds/xml_configuration/dynamic_types.rst
  docs/fastdds/xtypes/language_binding.rst
  docs/fastddsgen/dataTypes/dataTypes.rst
Labels: ci-pending

#919 [21557] Prepare for 2.10.5 release
  docs/conf.py
  docs/notes/notes.rst
  docs/notes/previous_versions/v2.10.4.rst
Labels: ci-pending

#920 [21416] Fix sphinx-toolbox version in requirements.txt
  docs/requirements.txt
Labels: ci-pending
