Repository eProsima/Fast-DDS-docs, pull requests merged in 2025-09, with the labels that each got.

#1105 [23508] Iterate over declared types processed with IDL Parser
  code/DDSCodeTester.cpp
  docs/03-exports/aliases-api.include
  docs/fastdds/xtypes/idl_parsing.rst
Labels: ci-pending

#1111 [23592] Add missing fields to transport descriptor documentation
  code/XMLTester.xml
  docs/fastdds/xml_configuration/transports.rst
Labels: ci-pending

#1116 [23657] Update Fast DDS Gen compatibility version on Fast DDS 3.2.x
  docs/notes/versions.rst
Labels: ci-pending

#1109 [22417] Add 2.14.5 release notes
  docs/notes/previous_versions/supported_versions.rst
  docs/notes/previous_versions/v2.14.5.rst
  docs/notes/versions.rst
Labels: ci-pending

#1103 Compile with warnings as errors in CI
  .github/workflows/config/build.meta
Labels: ci-pending

#1126 [23520] Update fastcdr release in Library dependencies section
  docs/notes/versions.rst
Labels: ci-pending

#1121 New commercial message.
  docs/02-formalia/titlepage.rst
Labels: ci-pending

#1133 New url for commercial message
  docs/02-formalia/titlepage.rst
Labels: ci-pending

#1115 [23653] Documentation debt: TCP sockets and CA extensions configuration
  docs/fastdds/security/auth_plugin/auth_plugin.rst
  docs/fastdds/use_cases/large_data/large_data.rst
Labels: ci-pending

#1135 [23704] Mark feed operations as a feature of Fast DDS Pro
  CMakeLists.txt
  code/CMakeLists.txt
  docs/fastdds/api_reference/dds_pim/rpc/rpc.rst
  docs/fastdds/api_reference/dds_pim/rpc/rpcclientreader.rst
  docs/fastdds/api_reference/dds_pim/rpc/rpcclientwriter.rst
  docs/fastdds/api_reference/dds_pim/rpc/rpcserverreader.rst
  docs/fastdds/api_reference/dds_pim/rpc/rpcserverwriter.rst
  docs/fastdds/rpc_dds/data_streaming/rpc_data_streaming_intro.rst
  docs/fastddsgen/rpc_calculator_feed_app/intro.rst
Labels: ci-pending, fast dds pro

#1129 [23647] Add documentation for IP mobility
  docs/fastdds/use_cases/dynamic_network_interfaces/dynamic_network_interfaces.rst
  docs/fastdds/use_cases/ip_mobility/ip_mobility.rst
  docs/fastdds/use_cases/tsn/tsn.rst
  docs/fastdds/use_cases/use_cases.rst
Labels: ready-to-merge, ci-pending, fast dds pro
